POST http://localhost/Events/login
Content-Type: "application/json"

{
    "username": "javier",
    "password": "javier"

}

###

POST  http://localhost/Events/users
Content-Type: "application/json"

{
    "username": "xavi_01",
    "password": "hola",
    "city": "barcelona",
    "country": "spain"
}
