POST http://localhost/events/login
Content-Type: "application/json"

{
    "username": "gerald",
    "password": "gerald"

}

###

POST  http://localhost/events/users
Content-Type: "application/json"

{
    "username": "gerald",
    "password": "gerald",
    "city": "barcelona",
    "country": "spain"
    
}
